Check/remove/create stat folder, and remove rms.auth, if it exists.

diff --git a/etc/Makefile.am b/etc/Makefile.am
--- a/etc/Makefile.am
+++ b/etc/Makefile.am
@@ -13,7 +13,21 @@ etcfiles = acihelp\
 SUBDIRS = . hooks
 
 install-data-hook:
-	$(mkinstalldirs) $(DESTDIR)$(RMS_SYSCONFDIR)
+	##If there is an existing stat folder, remove it to force a status update
+	@if test -d $(DESTDIR)$(RMS_SYSCONFDIR)/stat; then \
+	  echo " $(DESTDIR)$(RMS_SYSCONFDIR)/stat already exists; emptying to force status update"; \
+	  $(RM) -rf $(DESTDIR)$(RMS_SYSCONFDIR)/stat || true; \
+	fi
+	##If there is an existing rms.auth, remove is, it is no loner required
+	@if test -f $(DESTDIR)$(RMS_SYSCONFDIR)/rms.auth; then \
+	  echo " $(DESTDIR)$(RMS_SYSCONFDIR)/rms.auth is no longer required; deleting"; \
+	  $(RM) -f $(DESTDIR)$(RMS_SYSCONFDIR)/rms.auth || true; \
+	fi
+	##Re-create the stat folder, or create one if this is a new install
+	$(mkinstalldirs) $(DESTDIR)$(RMS_SYSCONFDIR)/stat
+	##On a new install, install the config files with their default names. 
+	##On an upgeade, if we find files with the same name, install these ones 
+	##with a .dist suffix, so we don't overwrite any user changed files.
 	@for p in $(etcfiles); do \
 	  if test -f $(DESTDIR)$(RMS_SYSCONFDIR)/$$p; then \
 	  echo " $(DESTDIR)$(RMS_SYSCONFDIR)/$$p already exists; installing new file as $$p.dist"; \
@@ -24,9 +38,11 @@ install-data-hook:
 	  fi; \
 	done
 
+#This makes distcheck happy by deleting the /etc/rmsgw folder on make uninstall
 uninstall-hook:
 	$(RM) -rf $(DESTDIR)$(RMS_SYSCONFDIR)
-	
+
+#This will replace variables in the .in files when make processes them
 edit = sed \
 	-e 's|@sbindir[@]|$(sbindir)|g' \
 	-e 's|@sysconfdir[@]|$(sysconfdir)|g' \
